CREATE TABLE users (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    USER_NAME VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) DEFAULT '{noop}default',
    ROLE VARCHAR(64) DEFAULT 'USER' CHECK (ROLE IN ('USER', 'ADMIN'))
);

CREATE TABLE note (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    TITLE VARCHAR NOT NULL CHECK (LENGTH(TITLE) > 2),
    CONTENT VARCHAR
);